CREATE TABLE class_sessions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id BIGINT,
    class_id   BIGINT,
    CONSTRAINT pk_class_sessions PRIMARY KEY (id)
);

CREATE TABLE class_students
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT,
    class_id   BIGINT,
    CONSTRAINT pk_class_students PRIMARY KEY (id)
);

CREATE TABLE classes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_name VARCHAR(100)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_classes PRIMARY KEY (id)
);

CREATE TABLE history_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    activity   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_history_log PRIMARY KEY (id)
);

CREATE TABLE sessions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    situation  VARCHAR(255),
    CONSTRAINT pk_sessions PRIMARY KEY (id)
);

CREATE TABLE students
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(100)                            NOT NULL,
    last_name  VARCHAR(100)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE user_classes
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT,
    class_id BIGINT,
    CONSTRAINT pk_user_classes PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname  VARCHAR(255),
    lastname   VARCHAR(255),
    email      VARCHAR(255)                            NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE class_sessions
    ADD CONSTRAINT FK_CLASS_SESSIONS_ON_CLASS FOREIGN KEY (class_id) REFERENCES classes (id);

ALTER TABLE class_sessions
    ADD CONSTRAINT FK_CLASS_SESSIONS_ON_SESSION FOREIGN KEY (session_id) REFERENCES sessions (id);

ALTER TABLE class_students
    ADD CONSTRAINT FK_CLASS_STUDENTS_ON_CLASS FOREIGN KEY (class_id) REFERENCES classes (id);

ALTER TABLE class_students
    ADD CONSTRAINT FK_CLASS_STUDENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE user_classes
    ADD CONSTRAINT FK_USER_CLASSES_ON_CLASS FOREIGN KEY (class_id) REFERENCES classes (id);

ALTER TABLE user_classes
    ADD CONSTRAINT FK_USER_CLASSES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);